# $$NAME$$ Dockerfile
#
# https://github.com/pseudomuto/dockerfiles/tree/master/$$NAME$$
#

FROM pseudomuto/base
MAINTAINER David Muto <david.muto@gmail.com>

# Update to invalidate image cache
ENV PMDF_REFRESHED_AT 20140722232113

CMD [""]
